name: Update Followers
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate followers list
        uses: jayqi/github-profile-followers-list-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          readme_path: ./README.md
